[package]
name = "libvpuppr"
version = "0.1.0"
edition = "2021"
authors = ["Tim Yuen<timothy.yuen22@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
argh = "0.1.12"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
    "time",
    "serde",
] }
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = [
    "serde",
] }
log = "0.4.20"
once_cell = "1.18"
rayon = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tot = "0.2"
youlog = "0.1.1"
